version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tenus_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tenus_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  tenus-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: tenus_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      PG_DATABASE: ${PG_DATABASE}
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tenus_network
    volumes:
      - app_logs:/app/logs

volumes:
  postgres_data:
  app_logs:

networks:
  tenus_network:
    driver: bridge
